name: CMake Pack and Multi-OS Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-pack:
    # Использование матрицы для запуска сборки одновременно на Linux и macOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            generator: "DEB;RPM"  # Собираем .deb и .rpm пакеты на Linux
          - os: macos-latest
            generator: "DragNDrop" # Собираем .dmg пакет на macOS

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Для сборки RPM-пакетов на Ubuntu утилите CPack нужен инструмент rpm
    - name: Install RPM tools (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm

    - name: Configure CMake
      run: |
        rm -rf _builds
        cmake -H. -B_builds -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCPACK_GENERATOR="${{ matrix.pack_generator }}"

    - name: Build and Pack
      run: cmake --build _builds --target package

    - name: Prepare Artifacts
      run: |
        mkdir artifacts
        # Переносим все сгенерированные пакеты (.deb, .rpm, .dmg) в папку artifacts
        mv _builds/*.deb artifacts/ 2>/dev/null || true
        mv _builds/*.rpm artifacts/ 2>/dev/null || true
        mv _builds/*.dmg artifacts/ 2>/dev/null || true
        mv _builds/*.tar.gz artifacts/ 2>/dev/null || true

    # Скрипт автоматически объединит файлы с обеих ОС и прикрепит их к одному релизу
    - name: Upload Artifacts to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
